server:
  port: 9001
spring:
  profiles:
    active: common
  cloud:
    config:
      uri: http://localhost:8001
  config:
    import: optional:configserver:http://localhost:8002
  application:
    name: jinghong-goods
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka
