server:
  port: 9001
spring:
  profiles:
    active: common
  application:
    name: jinghong-goods
  config:
    import: optional:configserver:http://localhost:8002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    prefer-ip-address: true
