server:
  port: 9002
spring:
  profiles:
    active: common
  application:
    name: jinghong-user
  config:
    import: optional:configserver:http://localhost:8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
