server:
  port: 8003
spring:
  cloud:
    config:
      uri: http://localhost:8002
    gateway:
      routes:
        - id: jinghong-goods
          uri: http://localhost:8003
          predicates:
            - Path=/jinghong/api/goods/**
  config:
    import: optional:configserver:http://localhost:8002
  application:
    name: jinghong-gateway
eureka:
  instance:
    hostname: jinghong-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
