pipeline {
    agent any
    environment {
        IMAGE_NAME = "jinghong-server"
        IMAGE_VERSION = "v1.1.0"
        CONTAINER_PORT = 8000
        CONTAINER_NAME = "jinghong-server"
        DOCKER_HUB_PAIR = credentials("docker-hub-pair")
        DOCKER_TAG_PREFIX = "chenxii81"
    }
    stages {
        stage('拉取代码') {
            steps {
                echo '🦊 从git仓库拉取代码'
                git branch: 'main', url: 'https://github.com/chenxii-coding/jinghong.git'
            }
        }
        stage('打包镜像') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_VERSION} ./${IMAGE_NAME}'
                echo '🥳 成功生成镜像！'
            }
        }
        stage('推送镜像') {
            steps {
                sh 'docker login -u ${DOCKER_HUB_PAIR_USR} -p ${DOCKER_HUB_PAIR_PSW}'
                sh 'docker tag ${IMAGE_NAME}:${IMAGE_VERSION} ${DOCKER_TAG_PREFIX}/${IMAGE_NAME}:${IMAGE_VERSION}'
                sh 'docker push ${DOCKER_TAG_PREFIX}/${IMAGE_NAME}:${IMAGE_VERSION}'
                echo '🥳 成功推送镜像'
            }
        }
        stage('启动容器') {
            steps {
                script {
                    def code = sh(
                            script: "docker ps -a | grep ${CONTAINER_NAME}",
                            returnStatus: true
                    )
                    if (code == 0) {
                        echo "⚠️ 找到 ${CONTAINER_NAME} 相关容器, 正在删除"
                        sh("docker ps -a | grep ${CONTAINER_NAME} | awk '{print \$1}' | xargs docker rm -f")
                    } else {
                        echo "没有找到 ${CONTAINER_NAME} 相关容器"
                    }
                    def code1 = sh(
                            script: "docker image ls | grep ${IMAGE_NAME}",
                            returnStatus: true
                    )
                    if (code1 == 0) {
                        echo "⚠️ 找到 ${IMAGE_NAME} 相关镜像, 正在删除"
                        sh("docker image ls | grep ${IMAGE_NAME} | awk '{print \$3}' | xargs docker rmi -f")
                    } else {
                        echo "没有找到 ${IMAGE_NAME} 相关镜像"
                    }
                }
                echo '🚗 🌬 历史镜像处理完毕'
                echo '💦 正在拉取镜像..'
                sh 'docker pull ${DOCKER_TAG_PREFIX}/${IMAGE_NAME}:${IMAGE_VERSION}'
                sh("docker run -dp ${CONTAINER_PORT}:${CONTAINER_PORT} --name ${CONTAINER_NAME} ${DOCKER_TAG_PREFIX}/${IMAGE_NAME}:${IMAGE_VERSION}")
                echo '🎉 部署成功！'
            }
        }
    }
    post {
        always {
            echo '流水线执行完成，已退出'
        }
    }
}
