spring:
  datasource:
    url: jdbc:postgresql://vm1:5432/jinghong
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath:*.xml
